### ISSUE TITLE
3.3.310.5r Disconnects players from a dedicated server when Greatwood Pipe is smoked.

### ISSUE THREAD

**Issue by kreezxil** [Rumaruka/Thaumic-Bases-Unofficial#16]
I erroneously posted this on Thaumcraft
:::::::::::::
In version 6.1.BETA26
A player of mine in my pack World of Dragons reported that while having the Great Wood pipe plus the tobacco pile in their inventory, when they go to smoke it, each time they are disconnected from the server.

In single player it works fine.

What the console says:
```
[11:13:00] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /64.31.193.174:53947
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_189651_aD()Lnet/minecraft/util/math/Vec3d;
        at com.rumaruka.tb.common.item.ItemSmokingPipe.onUsingTick(ItemSmokingPipe.java:103) ~[ItemSmokingPipe.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 9 more
```

cross posted at: https://github.com/Azanor/thaumcraft-beta/issues/1629
and originally received at: https://github.com/kreezxil/World-of-Dragons/issues/38

**Comment by kreezxil** [comment]
There is no full crash log because there is no crash only a server disconnect so the above snippet is relevant.

**Comment by Rumaruka** [comment]
I try fix this bug, but i don`t work  this Server D:
But I trying

**Comment by kreezxil** [comment]
What do you mean by "I don't work this server"?

Do you need a server to test it on?

You can do this easily in Eclipse, from the run menu select "run as server" and then when it's up, turn around and choose "run as client" then connect to localhost. Problem solved, you're now running against a server.

**Comment by kreezxil** [comment]
and ...
I can provide you with a test server, i like your mod(s) so why not.

**Comment by Rumaruka** [comment]
I try D:

**Comment by Rumaruka** [comment]
@kreezxil your offer about server still alive?

**Comment by kreezxil** [comment]
How much space do you need?

**Comment by Rumaruka** [comment]
@kreezxil how many space can you allocate?

**Comment by kreezxil** [comment]
I was prepared to slice you off a 4GB server with around 10GB of space to
help you to test your mod out. But if you need something more to do
something else like host a pack to actually be played or another game
entirely, we need to talk money.

**Comment by Rumaruka** [comment]
I think 4GB normal for test server @kreezxil

**Comment by kreezxil** [comment]
send me your email on my discord

**Comment by Renari** [comment]
```
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_189651_aD()Lnet/minecraft/util/math/Vec3d;
	at com.rumaruka.tb.common.item.ItemSmokingPipe.onUsingTick(ItemSmokingPipe.java:103) ~[ItemSmokingPipe.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
```

**Comment by Shadows-of-Fire** [comment]
You can fix this by switching your call to Entity#getForward to `Vec3d.fromPitchYaw(new Vec2f(Entity#rotationPitch, Entity#rotationYaw))`

**Comment by Rumaruka** [comment]
Fixed 
Thank @Shadows-of-Fire  and FTB_lag for Helps <3
