### ISSUE TITLE
Crash [TC6:B17] Thaumic Bases 3.1.250.1r

### ISSUE THREAD

**Issue by MachinegunMarty** [Rumaruka/Thaumic-Bases-Unofficial#2]
I updated Thaumcraft to Beta 17 and Thaumic Bases to 3.1.250.1r.

Got a crash on my client at startup.

Leaving Thaumcraft at BETA 17 and downgrading Thaumic Bases to 120.30b fixes the crash.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumic Bases (thaumicbases)
Caused by: java.lang.NoSuchFieldError: bucketDeath
    at com.rumaruka.tb.init.TBThaumonomicon.setup(TBThaumonomicon.java:353)
    at com.rumaruka.tb.core.TBCore.init(TBCore.java:105)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:626)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
    at net.minecraft.client.Minecraft.init(Minecraft.java:534)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3926)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Attached my client log:  
[latest.log](https://github.com/Rumaruka/Thaumic-Bases-Unofficial/files/2156335/latest.log)

Maybe because of some name changes in Thaumcraft ?

I hope it helps you out, to locate the problem !

Thanx for your time !

grtz,

MachinegunMarty

**Comment by Rumaruka** [comment]
I think, you're right
I see this problem tomorrow!
Beta 14 version work correct with TB 3.1.250.1r

**Comment by Rumaruka** [comment]
Nope, i see right now

**Comment by Rumaruka** [comment]
Yea, bucket is off in new version TC6:B17

**Comment by Rumaruka** [comment]
Okay, FIXED
Wait new build!
close #2
![2018-07-03_00 39 29](https://user-images.githubusercontent.com/8148679/42183049-d6f8cefe-7e59-11e8-92ad-bdf84d404caa.png)
