### ISSUE TITLE
Exception with enchantmentList?

### ISSUE THREAD

**Issue by LemADEC** [Rumaruka/Thaumic-Bases-Unofficial#5]
As of thaumicbases-3.1.255.2r-ForTC6B17, there's an exception during boot of a dedicated server.

```
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: java.lang.ClassCastException: Cannot cast net.minecraftforge.registries.NamespacedWrapper to [Lnet.minecraft.enchantment.Enchantment;
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at java.lang.Class.cast(Class.java:3369)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at DummyCore.Utils.MiscUtils.enchantmentList(MiscUtils.java:880)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.rumaruka.tb.utils.TBConfig.load(TBConfig.java:12)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at DummyCore.Core.Core.loadConfigForMod(Core.java:183)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at DummyCore.Core.Core.registerModAbsolute(Core.java:134)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at DummyCore.Core.Core.registerModAbsolute(Core.java:115)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.rumaruka.tb.core.TBCore.preInit(TBCore.java:75)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[17:58:10] [Server thread/INFO] [STDERR]: [DummyCore.Utils.MiscUtils:enchantmentList:882]: 	at java.lang.Thread.run(Thread.java:748)
```

This might be an issue in DummyCore itself?

**Comment by Rumaruka** [comment]
Yes, it`s exception core

**Comment by TheLMiffy1111** [comment]
Don't use that method. I forgot to remove it.
